// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxyMyokVjQrird1sVsAt-TdIrm44qJ3WU',
    appId: '1:883618836976:web:3ac3c1993b4e313cf5ed35',
    messagingSenderId: '883618836976',
    projectId: 'personal-finance-managem-32b03',
    authDomain: 'personal-finance-managem-32b03.firebaseapp.com',
    storageBucket: 'personal-finance-managem-32b03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxMS-trXJ1kbGbt95iBSW3td_muCISIeE',
    appId: '1:883618836976:android:2ff4d9e8e2473936f5ed35',
    messagingSenderId: '883618836976',
    projectId: 'personal-finance-managem-32b03',
    storageBucket: 'personal-finance-managem-32b03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9scxkhCo4R-bJveo0vkWezusA7pBU3IY',
    appId: '1:883618836976:ios:ed70c2daf09fb356f5ed35',
    messagingSenderId: '883618836976',
    projectId: 'personal-finance-managem-32b03',
    storageBucket: 'personal-finance-managem-32b03.appspot.com',
    iosBundleId: 'com.example.personalFinanceManagementApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9scxkhCo4R-bJveo0vkWezusA7pBU3IY',
    appId: '1:883618836976:ios:7d51d298c6adc429f5ed35',
    messagingSenderId: '883618836976',
    projectId: 'personal-finance-managem-32b03',
    storageBucket: 'personal-finance-managem-32b03.appspot.com',
    iosBundleId: 'com.example.personalFinanceManagementApplication.RunnerTests',
  );
}
